//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exportadorfacturas.WsAirtech {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://airtechsa.com.ar/", ConfigurationName="WsAirtech.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_motivos_recambio_eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_motivos_recambio_eliminar(string codigoempresa, int idmotivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_motivos_recambio_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_motivos_recambio_listar(string codigoempresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_parametros_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_parametros_listar(string codigoempresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_parametros_actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_parametros_actualizar(string codigoempresa, int id, string nombreempresa, int controlstockbultos, string carpetacliente, int monitoreo_nuevo_activado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_cierrecaja_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_cierrecaja_listar(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_cierrecaja_actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_cierrecaja_actualizar(string codigoempresa, string idcierre, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_informe_ventaproducto_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_informe_ventaproducto_listar(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_informe_totalreparto_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_informe_totalreparto_listar(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_informe_recargas_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_informe_recargas_listar(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stock_detalle_prestamos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stock_detalle_prestamos(string codigoempresa, string fecha, int idreparto, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_infogeneral_avancegeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_infogeneral_avancegeneral(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/FACTURACION_getpedidosafacturar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FACTURACION_getpedidosafacturar(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/FACTURACION_setpedidofacturado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FACTURACION_setpedidofacturado(string BDCliente, string idpedido, string codmov, string nromov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/puedo_trabajar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int puedo_trabajar(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarDiasPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarDiasPrestamo(int dias_prestamo, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/descarga_auditoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet descarga_auditoria(string BDCLIENTE, string fecha_hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/get_novedades_gral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void get_novedades_gral(string codigoempresa, string version, string app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/get_version", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void get_version();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_Mensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_Mensaje(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_Mensaje_CI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_Mensaje_CI(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_MensajeII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_MensajeII(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_Mensaje_CI_II", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_Mensaje_CI_II(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Existe_Cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Existe_Cliente(double Idcliente, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_Cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_Cliente(double Nrocta, string Nombre, string Direcc, string locali, string telefono, int tipocli, int cndiva, string condpago, double cuotafc, double cumplimientofc, int tienefc, string nrocuit, int retiraenvases, double porciibb, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Borrar_DatosCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Borrar_DatosCliente(double Nrocta, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_RecargasEquipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar_RecargasEquipos(int Idreparto, string idproducto, string nroserie, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarRecargas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarRecargas(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarRecargaStockEquipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarRecargaStockEquipo(string nroserie, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarCliente(double Idcliente, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarMensaje(double Idllamada, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarComodato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarComodato(double IdCliente, string idproducto, string tipo, double cantidad, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarPrestados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarPrestados(double IdCliente, string idproducto, System.DateTime Vencimiento, double cantidad, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarPrecios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarPrecios(double IdCliente, string idproducto, double precio, string tipo, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarLlamadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarLlamadas(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarLlamadasWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarLlamadasWeb(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarEquipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarEquipos(double Idcliente, string Idproducto, string Nroserie, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarAccionesFC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarAccionesFC(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarMotivosNoCompra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarMotivosNoCompra(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarMotivosRecambios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarMotivosRecambios(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarAccionesFCPrecios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarAccionesFCPrecios(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarAccionesFCPrecios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarAccionesFCPrecios(double idaccion, double precio, string idproducto, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarAccionesFC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarAccionesFC(double idaccion, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarAccionesFCPrecios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarAccionesFCPrecios(double idaccion, double precio, string idproducto, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarAccionesFC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarAccionesFC(double idaccion, string descripcion, int requiere_equipo, int tiene_precio, string idproducto, string destino, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizaAlertas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizaAlertas(System.Data.DataSet oDs, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizaAlertasII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizaAlertasII(System.Data.DataSet oDs, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EjecutarTarea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EjecutarTarea(string Tarea, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EjecutarTareaII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EjecutarTareaII(string Tarea, string BDCliente, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizaCtaCte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizaCtaCte(System.Data.DataSet oDs, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizaCtaCteDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizaCtaCteDetalle(System.Data.DataSet oDs, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizaMadresHijas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizaMadresHijas(System.Data.DataSet oDs, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizaTalonarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizaTalonarios(System.Data.DataSet oDs, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ListarQRY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarQRY(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarSolicitud", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertarSolicitud(string Nombre, string Mail, string Sol, string Emp, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/getVersionMensajero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getVersionMensajero(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/getConfiguracionIni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getConfiguracionIni(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/setConfiguracionIni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setConfiguracionIni(
                    string BDCliente, 
                    string valor1, 
                    string valor2, 
                    string valor3, 
                    string valor4, 
                    string valor5, 
                    string valor6, 
                    string valor7, 
                    string valor8, 
                    string valor9, 
                    string valor10, 
                    string valor11, 
                    string valor12, 
                    string valor13, 
                    string valor14, 
                    string valor15);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/versionGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string versionGet(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/versionPosponer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string versionPosponer(string idversion, string usuario, string fecha_posponer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/VersionHabilitarInsTerminales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VersionHabilitarInsTerminales(string idversion, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/versionIns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string versionIns(string version, string url_version, string url_exe, string url_reporte, string url_auxiliar, string url_query, string url_documentacion, string url_mensajero, string url_alertas, string url_ajustes, string url_facturador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/versionInsCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string versionInsCliente(string BDCliente, string version, string url_version, string url_exe, string url_reporte, string url_auxiliar, string url_query, string url_documentacion, string url_mensajero, string url_alertas, string url_ajustes, string url_facturador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/versionInsLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string versionInsLog(string BDCliente, string version, string descarga, string url_descarga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizadorInsLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizadorInsLog(string BdCliente, string tipo, string bd, string carpeta, string archivo, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizadorInsLog2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizadorInsLog2(string BdCliente, string tipo, string bd, string carpeta, string archivo, string mensaje, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ActualizadorGetLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizadorGetLog(string BdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/actualizaWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string actualizaWeb(string BDCliente, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarUrlPlanB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarUrlPlanB(string fecha, string url1, string url2, string bdweb, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ListarEstadoSincro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarEstadoSincro(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Sincronizar_Archivos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Sincronizar_Archivos(string Fecha_Visita, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/borrar_fecha_sincro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void borrar_fecha_sincro(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/MaximoMovimientosPrestamos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MaximoMovimientosPrestamos(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarPrestamo(string cliente, string producto, string cantidad, string fecha, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ModificarPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificarPrestamo(string idprestamo, string cantidad, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ModificarPrestamoRetiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificarPrestamoRetiro(string idprestamoret, string cantidad, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarPrestamo(string idprestamo, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarPrestamoRetiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarPrestamoRetiro(string idprestamoret, string cliente, string producto, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarPrestamosWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarPrestamosWeb(string cliente, string producto, string fecha, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/MaximoMovimientosCajaAjustes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MaximoMovimientosCajaAjustes(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarMovimientoAjuste", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarMovimientoAjuste(string cliente, string descripcion, string importe, string fecha, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ModificarCaja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificarCaja(string idmovimiento, string importe, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ModificarCajaAjustes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificarCajaAjustes(string idmovajuste, string importe, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarMovimientoCaja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarMovimientoCaja(string idmovimiento, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/EliminarCajaAjuste", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarCajaAjuste(string idmovajuste, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarCajaWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarCajaWeb(string cliente, string fecha, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ajustes_descarga_saldos_caja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ajustes_descarga_saldos_caja(string cliente, string fecha_hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ajustes_descarga_saldos_envases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ajustes_descarga_saldos_envases(string cliente, string fecha_hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/getDirLatLon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getDirLatLon(string direccion, int unicoResultado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/ConsultarEtapasActivas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarEtapasActivas(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarResultadoSeguimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertarResultadoSeguimiento(string etapa, string criterio, string fecha, string reparto, string producto, string basecalculo, string valor, string porcentaje, string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/InsertarRegistroActividad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertarRegistroActividad(string BDCliente, string usuario, string nodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_insertar_error", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void autocierre_insertar_error(string BDCliente, int reparto, string clase, string funcion, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_pedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_pedidos(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_pedidosdetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_pedidosdetalle(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_datosadicionales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_datosadicionales(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_novedadesenc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_novedadesenc(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_retiros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_retiros(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_recambios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_recambios(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_stockrecargas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_stockrecargas(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_movimientoscaja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_movimientoscaja(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_novedadesitem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_novedadesitem(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_nocompradores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_nocompradores(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_movimientosequipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_movimientosequipos(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/autocierre_descargar_promos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet autocierre_descargar_promos(string BDCliente, int reparto, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Actualizador_Scripts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Actualizador_Scripts(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Insertar_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Insertar_status(string BDCliente, long script_id, string status, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/Version_scripts_exclusiones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Version_scripts_exclusiones(string BDCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_validausuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_validausuario(string codigoempresa, string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_usuario_actualizar_variables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_usuario_actualizar_variables(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_validaempresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_validaempresa(string codigoempresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_ventasporreparto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_ventasporreparto(string codigoempresa, string idrepartodesde, string idrepartohasta, string fechadesde, string fechahasta, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_infogeneral_nocompradores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_infogeneral_nocompradores(string codigoempresa, string idreparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_infogeneral_compradores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_infogeneral_compradores(string codigoempresa, string idreparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_infogeneral_intervalos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_infogeneral_intervalos(string codigoempresa, int tipo, string idreparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_cobradoporreparto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_cobradoporreparto(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, int tiporesultado, string condicionpago, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_listarpedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_listarpedidos(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string productos, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_controlruta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_controlruta(string codigoempresa, string fecha, int idreparto, int tiporesultado, int orden, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontrol(string codigoempresa, string fecha, int idreparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontroldetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontroldetalle(string codigoempresa, int idreparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontrolequipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontrolequipos(string codigoempresa, int idreparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontrolhistoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontrolhistoria(string codigoempresa, int idreparto, string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontroleliminarequipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontroleliminarequipo(string codigoempresa, int idreparto, long idrecarga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontrolinsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontrolinsertar(string codigoempresa, int idreparto, string idproducto, long lleno_bulto, long lleno_suelto, long vacio_bulto, long vacio_suelto, long desdereparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_stockcontrolinsertarequipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_stockcontrolinsertarequipo(string codigoempresa, int idreparto, string idproducto, string nro_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_mensajeinsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_mensajeinsertar(string codigoempresa, int idreparto, string idusuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_repartosporsupervisor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_repartosporsupervisor(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_insertarreparto_supervisor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_insertarreparto_supervisor(string codigoempresa, string idusuario, string idsupervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_borrarreparto_supervisor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_borrarreparto_supervisor(string codigoempresa, string idusuario, string idsupervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_mensajeborrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_mensajeborrar(string codigoempresa, string idmensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_mensajelistar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_mensajelistar(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_getubicacion_repartos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_getubicacion_repartos(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_getruta_real", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_getruta_real(string codigoempresa, string fecha, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_topesfiadolistar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_topesfiadolistar(string codigoempresa, string idrepartodesde, string idrepartohasta, int clientesdeldia, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_topesfiado_actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_topesfiado_actualizar(string codigoempresa, string tope_aviso, string tope_bloqueo, string minimo_cobrar, string idcliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_agregarruta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_agregarruta(string codigoempresa, string usuario, string rtoprimario, string diaprimario, string rtosecundario, string diasecundario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_agregarrutaeliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_agregarrutaeliminar(string codigoempresa, string usuario, string idcambioruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_agregarrutalistar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_agregarrutalistar(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_informaciongeneralgrilla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_informaciongeneralgrilla(string codigoempresa, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_usuarioactualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_usuarioactualizar(
                    string codigoempresa, 
                    string idusuario, 
                    string idperfil, 
                    string nombre, 
                    string usuario, 
                    string idvendedor, 
                    int editaprecio, 
                    int sincargo, 
                    int minutosmax, 
                    string passsup, 
                    int habfc, 
                    int repuniversal, 
                    int habremito, 
                    int habfactura, 
                    int habfacturaelectronica, 
                    int habrecibo, 
                    int habremitocontado, 
                    int habfacrempagocontado, 
                    string iibb, 
                    string pass, 
                    int trabaja_madrugada, 
                    int oculta_totales_estadistica, 
                    int oculta_novisitar, 
                    string idsupervisor, 
                    int total_clientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_usuarioeliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_usuarioeliminar(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_usuarioslistar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_usuarioslistar(string codigoempresa, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_usuarios_modifmasivapass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_usuarios_modifmasivapass(string codigoempresa, int idperfil, int tipopass, string pass, string idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_motivos_nocompra_actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_motivos_nocompra_actualizar(string codigoempresa, int idmotivo, string descripcion, int orden, int cierrallamado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_motivos_nocompra_eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_motivos_nocompra_eliminar(string codigoempresa, int idmotivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_motivos_nocompra_listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_motivos_nocompra_listar(string codigoempresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://airtechsa.com.ar/web_motivos_recambio_actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void web_motivos_recambio_actualizar(string codigoempresa, int idmotivo, string descripcion, int orden);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : exportadorfacturas.WsAirtech.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<exportadorfacturas.WsAirtech.Service1Soap>, exportadorfacturas.WsAirtech.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void web_motivos_recambio_eliminar(string codigoempresa, int idmotivo) {
            base.Channel.web_motivos_recambio_eliminar(codigoempresa, idmotivo);
        }
        
        public void web_motivos_recambio_listar(string codigoempresa) {
            base.Channel.web_motivos_recambio_listar(codigoempresa);
        }
        
        public void web_parametros_listar(string codigoempresa) {
            base.Channel.web_parametros_listar(codigoempresa);
        }
        
        public void web_parametros_actualizar(string codigoempresa, int id, string nombreempresa, int controlstockbultos, string carpetacliente, int monitoreo_nuevo_activado) {
            base.Channel.web_parametros_actualizar(codigoempresa, id, nombreempresa, controlstockbultos, carpetacliente, monitoreo_nuevo_activado);
        }
        
        public void web_cierrecaja_listar(string codigoempresa, string idusuario) {
            base.Channel.web_cierrecaja_listar(codigoempresa, idusuario);
        }
        
        public void web_cierrecaja_actualizar(string codigoempresa, string idcierre, string estado) {
            base.Channel.web_cierrecaja_actualizar(codigoempresa, idcierre, estado);
        }
        
        public void web_informe_ventaproducto_listar(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string idusuario) {
            base.Channel.web_informe_ventaproducto_listar(codigoempresa, idrepartodesde, idrepartohasta, fechadesde, fechahasta, idusuario);
        }
        
        public void web_informe_totalreparto_listar(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string idusuario) {
            base.Channel.web_informe_totalreparto_listar(codigoempresa, idrepartodesde, idrepartohasta, fechadesde, fechahasta, idusuario);
        }
        
        public void web_informe_recargas_listar(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string idusuario) {
            base.Channel.web_informe_recargas_listar(codigoempresa, idrepartodesde, idrepartohasta, fechadesde, fechahasta, idusuario);
        }
        
        public void web_stock_detalle_prestamos(string codigoempresa, string fecha, int idreparto, string idusuario) {
            base.Channel.web_stock_detalle_prestamos(codigoempresa, fecha, idreparto, idusuario);
        }
        
        public void web_infogeneral_avancegeneral(string codigoempresa, string idusuario) {
            base.Channel.web_infogeneral_avancegeneral(codigoempresa, idusuario);
        }
        
        public System.Data.DataSet FACTURACION_getpedidosafacturar(string BDCliente) {
            return base.Channel.FACTURACION_getpedidosafacturar(BDCliente);
        }
        
        public bool FACTURACION_setpedidofacturado(string BDCliente, string idpedido, string codmov, string nromov) {
            return base.Channel.FACTURACION_setpedidofacturado(BDCliente, idpedido, codmov, nromov);
        }
        
        public int puedo_trabajar(string BDCliente) {
            return base.Channel.puedo_trabajar(BDCliente);
        }
        
        public string InsertarDiasPrestamo(int dias_prestamo, string BDCliente) {
            return base.Channel.InsertarDiasPrestamo(dias_prestamo, BDCliente);
        }
        
        public System.Data.DataSet descarga_auditoria(string BDCLIENTE, string fecha_hasta) {
            return base.Channel.descarga_auditoria(BDCLIENTE, fecha_hasta);
        }
        
        public void get_novedades_gral(string codigoempresa, string version, string app) {
            base.Channel.get_novedades_gral(codigoempresa, version, app);
        }
        
        public void get_version() {
            base.Channel.get_version();
        }
        
        public string Insertar_Mensaje(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente) {
            return base.Channel.Insertar_Mensaje(Idllamada, Idcliente, mensaje, Idreparto, BDCliente);
        }
        
        public string Insertar_Mensaje_CI(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente) {
            return base.Channel.Insertar_Mensaje_CI(Idllamada, Idcliente, mensaje, Idreparto, BDCliente);
        }
        
        public string Insertar_MensajeII(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente, string fecha) {
            return base.Channel.Insertar_MensajeII(Idllamada, Idcliente, mensaje, Idreparto, BDCliente, fecha);
        }
        
        public string Insertar_Mensaje_CI_II(double Idllamada, double Idcliente, string mensaje, int Idreparto, string BDCliente, string fecha) {
            return base.Channel.Insertar_Mensaje_CI_II(Idllamada, Idcliente, mensaje, Idreparto, BDCliente, fecha);
        }
        
        public bool Existe_Cliente(double Idcliente, string BDCliente) {
            return base.Channel.Existe_Cliente(Idcliente, BDCliente);
        }
        
        public string Insertar_Cliente(double Nrocta, string Nombre, string Direcc, string locali, string telefono, int tipocli, int cndiva, string condpago, double cuotafc, double cumplimientofc, int tienefc, string nrocuit, int retiraenvases, double porciibb, string BDCliente) {
            return base.Channel.Insertar_Cliente(Nrocta, Nombre, Direcc, locali, telefono, tipocli, cndiva, condpago, cuotafc, cumplimientofc, tienefc, nrocuit, retiraenvases, porciibb, BDCliente);
        }
        
        public string Borrar_DatosCliente(double Nrocta, string BDCliente) {
            return base.Channel.Borrar_DatosCliente(Nrocta, BDCliente);
        }
        
        public string Insertar_RecargasEquipos(int Idreparto, string idproducto, string nroserie, string BDCliente) {
            return base.Channel.Insertar_RecargasEquipos(Idreparto, idproducto, nroserie, BDCliente);
        }
        
        public System.Data.DataSet ConsultarRecargas(string BDCliente) {
            return base.Channel.ConsultarRecargas(BDCliente);
        }
        
        public string EliminarRecargaStockEquipo(string nroserie, string BDCliente) {
            return base.Channel.EliminarRecargaStockEquipo(nroserie, BDCliente);
        }
        
        public string EliminarCliente(double Idcliente, string BDCliente) {
            return base.Channel.EliminarCliente(Idcliente, BDCliente);
        }
        
        public string EliminarMensaje(double Idllamada, string BDCliente) {
            return base.Channel.EliminarMensaje(Idllamada, BDCliente);
        }
        
        public string InsertarComodato(double IdCliente, string idproducto, string tipo, double cantidad, string BDCliente) {
            return base.Channel.InsertarComodato(IdCliente, idproducto, tipo, cantidad, BDCliente);
        }
        
        public string InsertarPrestados(double IdCliente, string idproducto, System.DateTime Vencimiento, double cantidad, string BDCliente) {
            return base.Channel.InsertarPrestados(IdCliente, idproducto, Vencimiento, cantidad, BDCliente);
        }
        
        public string InsertarPrecios(double IdCliente, string idproducto, double precio, string tipo, string BDCliente) {
            return base.Channel.InsertarPrecios(IdCliente, idproducto, precio, tipo, BDCliente);
        }
        
        public System.Data.DataSet ConsultarLlamadas(string BDCliente) {
            return base.Channel.ConsultarLlamadas(BDCliente);
        }
        
        public System.Data.DataSet ConsultarLlamadasWeb(string BDCliente) {
            return base.Channel.ConsultarLlamadasWeb(BDCliente);
        }
        
        public string InsertarEquipos(double Idcliente, string Idproducto, string Nroserie, string BDCliente) {
            return base.Channel.InsertarEquipos(Idcliente, Idproducto, Nroserie, BDCliente);
        }
        
        public System.Data.DataSet ConsultarAccionesFC(string BDCliente) {
            return base.Channel.ConsultarAccionesFC(BDCliente);
        }
        
        public System.Data.DataSet ConsultarMotivosNoCompra(string BDCliente) {
            return base.Channel.ConsultarMotivosNoCompra(BDCliente);
        }
        
        public System.Data.DataSet ConsultarMotivosRecambios(string BDCliente) {
            return base.Channel.ConsultarMotivosRecambios(BDCliente);
        }
        
        public System.Data.DataSet ConsultarAccionesFCPrecios(string BDCliente) {
            return base.Channel.ConsultarAccionesFCPrecios(BDCliente);
        }
        
        public string EliminarAccionesFCPrecios(double idaccion, double precio, string idproducto, string BDCliente) {
            return base.Channel.EliminarAccionesFCPrecios(idaccion, precio, idproducto, BDCliente);
        }
        
        public string EliminarAccionesFC(double idaccion, string BDCliente) {
            return base.Channel.EliminarAccionesFC(idaccion, BDCliente);
        }
        
        public string InsertarAccionesFCPrecios(double idaccion, double precio, string idproducto, string BDCliente) {
            return base.Channel.InsertarAccionesFCPrecios(idaccion, precio, idproducto, BDCliente);
        }
        
        public string InsertarAccionesFC(double idaccion, string descripcion, int requiere_equipo, int tiene_precio, string idproducto, string destino, string BDCliente) {
            return base.Channel.InsertarAccionesFC(idaccion, descripcion, requiere_equipo, tiene_precio, idproducto, destino, BDCliente);
        }
        
        public string ActualizaAlertas(System.Data.DataSet oDs, string BDCliente) {
            return base.Channel.ActualizaAlertas(oDs, BDCliente);
        }
        
        public string ActualizaAlertasII(System.Data.DataSet oDs, string BDCliente) {
            return base.Channel.ActualizaAlertasII(oDs, BDCliente);
        }
        
        public string EjecutarTarea(string Tarea, string BDCliente) {
            return base.Channel.EjecutarTarea(Tarea, BDCliente);
        }
        
        public string EjecutarTareaII(string Tarea, string BDCliente, string Fecha) {
            return base.Channel.EjecutarTareaII(Tarea, BDCliente, Fecha);
        }
        
        public string ActualizaCtaCte(System.Data.DataSet oDs, string BDCliente) {
            return base.Channel.ActualizaCtaCte(oDs, BDCliente);
        }
        
        public string ActualizaCtaCteDetalle(System.Data.DataSet oDs, string BDCliente) {
            return base.Channel.ActualizaCtaCteDetalle(oDs, BDCliente);
        }
        
        public string ActualizaMadresHijas(System.Data.DataSet oDs, string BDCliente) {
            return base.Channel.ActualizaMadresHijas(oDs, BDCliente);
        }
        
        public string ActualizaTalonarios(System.Data.DataSet oDs, string BDCliente) {
            return base.Channel.ActualizaTalonarios(oDs, BDCliente);
        }
        
        public System.Data.DataSet ListarQRY(string BDCliente) {
            return base.Channel.ListarQRY(BDCliente);
        }
        
        public void InsertarSolicitud(string Nombre, string Mail, string Sol, string Emp, string BDCliente) {
            base.Channel.InsertarSolicitud(Nombre, Mail, Sol, Emp, BDCliente);
        }
        
        public string getVersionMensajero(string BDCliente) {
            return base.Channel.getVersionMensajero(BDCliente);
        }
        
        public string getConfiguracionIni(string BDCliente) {
            return base.Channel.getConfiguracionIni(BDCliente);
        }
        
        public string setConfiguracionIni(
                    string BDCliente, 
                    string valor1, 
                    string valor2, 
                    string valor3, 
                    string valor4, 
                    string valor5, 
                    string valor6, 
                    string valor7, 
                    string valor8, 
                    string valor9, 
                    string valor10, 
                    string valor11, 
                    string valor12, 
                    string valor13, 
                    string valor14, 
                    string valor15) {
            return base.Channel.setConfiguracionIni(BDCliente, valor1, valor2, valor3, valor4, valor5, valor6, valor7, valor8, valor9, valor10, valor11, valor12, valor13, valor14, valor15);
        }
        
        public string versionGet(string BDCliente) {
            return base.Channel.versionGet(BDCliente);
        }
        
        public string versionPosponer(string idversion, string usuario, string fecha_posponer) {
            return base.Channel.versionPosponer(idversion, usuario, fecha_posponer);
        }
        
        public string VersionHabilitarInsTerminales(string idversion, string usuario) {
            return base.Channel.VersionHabilitarInsTerminales(idversion, usuario);
        }
        
        public string versionIns(string version, string url_version, string url_exe, string url_reporte, string url_auxiliar, string url_query, string url_documentacion, string url_mensajero, string url_alertas, string url_ajustes, string url_facturador) {
            return base.Channel.versionIns(version, url_version, url_exe, url_reporte, url_auxiliar, url_query, url_documentacion, url_mensajero, url_alertas, url_ajustes, url_facturador);
        }
        
        public string versionInsCliente(string BDCliente, string version, string url_version, string url_exe, string url_reporte, string url_auxiliar, string url_query, string url_documentacion, string url_mensajero, string url_alertas, string url_ajustes, string url_facturador) {
            return base.Channel.versionInsCliente(BDCliente, version, url_version, url_exe, url_reporte, url_auxiliar, url_query, url_documentacion, url_mensajero, url_alertas, url_ajustes, url_facturador);
        }
        
        public string versionInsLog(string BDCliente, string version, string descarga, string url_descarga) {
            return base.Channel.versionInsLog(BDCliente, version, descarga, url_descarga);
        }
        
        public string ActualizadorInsLog(string BdCliente, string tipo, string bd, string carpeta, string archivo, string mensaje) {
            return base.Channel.ActualizadorInsLog(BdCliente, tipo, bd, carpeta, archivo, mensaje);
        }
        
        public string ActualizadorInsLog2(string BdCliente, string tipo, string bd, string carpeta, string archivo, string mensaje, string version) {
            return base.Channel.ActualizadorInsLog2(BdCliente, tipo, bd, carpeta, archivo, mensaje, version);
        }
        
        public string ActualizadorGetLog(string BdCliente) {
            return base.Channel.ActualizadorGetLog(BdCliente);
        }
        
        public string actualizaWeb(string BDCliente, string query) {
            return base.Channel.actualizaWeb(BDCliente, query);
        }
        
        public string InsertarUrlPlanB(string fecha, string url1, string url2, string bdweb, string BDCliente) {
            return base.Channel.InsertarUrlPlanB(fecha, url1, url2, bdweb, BDCliente);
        }
        
        public System.Data.DataSet ListarEstadoSincro(string BDCliente) {
            return base.Channel.ListarEstadoSincro(BDCliente);
        }
        
        public string Sincronizar_Archivos(string Fecha_Visita, string BDCliente) {
            return base.Channel.Sincronizar_Archivos(Fecha_Visita, BDCliente);
        }
        
        public void borrar_fecha_sincro(string BDCliente) {
            base.Channel.borrar_fecha_sincro(BDCliente);
        }
        
        public string MaximoMovimientosPrestamos(string BDCliente) {
            return base.Channel.MaximoMovimientosPrestamos(BDCliente);
        }
        
        public string InsertarPrestamo(string cliente, string producto, string cantidad, string fecha, string BDCliente) {
            return base.Channel.InsertarPrestamo(cliente, producto, cantidad, fecha, BDCliente);
        }
        
        public string ModificarPrestamo(string idprestamo, string cantidad, string BDCliente) {
            return base.Channel.ModificarPrestamo(idprestamo, cantidad, BDCliente);
        }
        
        public string ModificarPrestamoRetiro(string idprestamoret, string cantidad, string BDCliente) {
            return base.Channel.ModificarPrestamoRetiro(idprestamoret, cantidad, BDCliente);
        }
        
        public string EliminarPrestamo(string idprestamo, string BDCliente) {
            return base.Channel.EliminarPrestamo(idprestamo, BDCliente);
        }
        
        public string EliminarPrestamoRetiro(string idprestamoret, string cliente, string producto, string BDCliente) {
            return base.Channel.EliminarPrestamoRetiro(idprestamoret, cliente, producto, BDCliente);
        }
        
        public System.Data.DataSet ConsultarPrestamosWeb(string cliente, string producto, string fecha, string BDCliente) {
            return base.Channel.ConsultarPrestamosWeb(cliente, producto, fecha, BDCliente);
        }
        
        public string MaximoMovimientosCajaAjustes(string BDCliente) {
            return base.Channel.MaximoMovimientosCajaAjustes(BDCliente);
        }
        
        public string InsertarMovimientoAjuste(string cliente, string descripcion, string importe, string fecha, string BDCliente) {
            return base.Channel.InsertarMovimientoAjuste(cliente, descripcion, importe, fecha, BDCliente);
        }
        
        public string ModificarCaja(string idmovimiento, string importe, string BDCliente) {
            return base.Channel.ModificarCaja(idmovimiento, importe, BDCliente);
        }
        
        public string ModificarCajaAjustes(string idmovajuste, string importe, string BDCliente) {
            return base.Channel.ModificarCajaAjustes(idmovajuste, importe, BDCliente);
        }
        
        public string EliminarMovimientoCaja(string idmovimiento, string BDCliente) {
            return base.Channel.EliminarMovimientoCaja(idmovimiento, BDCliente);
        }
        
        public string EliminarCajaAjuste(string idmovajuste, string BDCliente) {
            return base.Channel.EliminarCajaAjuste(idmovajuste, BDCliente);
        }
        
        public System.Data.DataSet ConsultarCajaWeb(string cliente, string fecha, string BDCliente) {
            return base.Channel.ConsultarCajaWeb(cliente, fecha, BDCliente);
        }
        
        public System.Data.DataSet ajustes_descarga_saldos_caja(string cliente, string fecha_hasta) {
            return base.Channel.ajustes_descarga_saldos_caja(cliente, fecha_hasta);
        }
        
        public System.Data.DataSet ajustes_descarga_saldos_envases(string cliente, string fecha_hasta) {
            return base.Channel.ajustes_descarga_saldos_envases(cliente, fecha_hasta);
        }
        
        public string getDirLatLon(string direccion, int unicoResultado) {
            return base.Channel.getDirLatLon(direccion, unicoResultado);
        }
        
        public System.Data.DataSet ConsultarEtapasActivas(string BDCliente) {
            return base.Channel.ConsultarEtapasActivas(BDCliente);
        }
        
        public void InsertarResultadoSeguimiento(string etapa, string criterio, string fecha, string reparto, string producto, string basecalculo, string valor, string porcentaje, string BDCliente) {
            base.Channel.InsertarResultadoSeguimiento(etapa, criterio, fecha, reparto, producto, basecalculo, valor, porcentaje, BDCliente);
        }
        
        public void InsertarRegistroActividad(string BDCliente, string usuario, string nodo) {
            base.Channel.InsertarRegistroActividad(BDCliente, usuario, nodo);
        }
        
        public void autocierre_insertar_error(string BDCliente, int reparto, string clase, string funcion, string error) {
            base.Channel.autocierre_insertar_error(BDCliente, reparto, clase, funcion, error);
        }
        
        public System.Data.DataSet autocierre_descargar_pedidos(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_pedidos(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_pedidosdetalle(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_pedidosdetalle(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_datosadicionales(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_datosadicionales(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_novedadesenc(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_novedadesenc(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_retiros(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_retiros(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_recambios(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_recambios(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_stockrecargas(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_stockrecargas(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_movimientoscaja(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_movimientoscaja(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_novedadesitem(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_novedadesitem(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_nocompradores(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_nocompradores(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_movimientosequipos(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_movimientosequipos(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet autocierre_descargar_promos(string BDCliente, int reparto, string fecha) {
            return base.Channel.autocierre_descargar_promos(BDCliente, reparto, fecha);
        }
        
        public System.Data.DataSet Actualizador_Scripts(string BDCliente) {
            return base.Channel.Actualizador_Scripts(BDCliente);
        }
        
        public void Insertar_status(string BDCliente, long script_id, string status, string descripcion) {
            base.Channel.Insertar_status(BDCliente, script_id, status, descripcion);
        }
        
        public System.Data.DataSet Version_scripts_exclusiones(string BDCliente) {
            return base.Channel.Version_scripts_exclusiones(BDCliente);
        }
        
        public void web_validausuario(string codigoempresa, string usuario, string pass) {
            base.Channel.web_validausuario(codigoempresa, usuario, pass);
        }
        
        public void web_usuario_actualizar_variables(string codigoempresa, string idusuario) {
            base.Channel.web_usuario_actualizar_variables(codigoempresa, idusuario);
        }
        
        public void web_validaempresa(string codigoempresa) {
            base.Channel.web_validaempresa(codigoempresa);
        }
        
        public void web_ventasporreparto(string codigoempresa, string idrepartodesde, string idrepartohasta, string fechadesde, string fechahasta, string idusuario) {
            base.Channel.web_ventasporreparto(codigoempresa, idrepartodesde, idrepartohasta, fechadesde, fechahasta, idusuario);
        }
        
        public void web_infogeneral_nocompradores(string codigoempresa, string idreparto) {
            base.Channel.web_infogeneral_nocompradores(codigoempresa, idreparto);
        }
        
        public void web_infogeneral_compradores(string codigoempresa, string idreparto) {
            base.Channel.web_infogeneral_compradores(codigoempresa, idreparto);
        }
        
        public void web_infogeneral_intervalos(string codigoempresa, int tipo, string idreparto) {
            base.Channel.web_infogeneral_intervalos(codigoempresa, tipo, idreparto);
        }
        
        public void web_cobradoporreparto(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, int tiporesultado, string condicionpago, string idusuario) {
            base.Channel.web_cobradoporreparto(codigoempresa, idrepartodesde, idrepartohasta, fechadesde, fechahasta, tiporesultado, condicionpago, idusuario);
        }
        
        public void web_listarpedidos(string codigoempresa, int idrepartodesde, int idrepartohasta, string fechadesde, string fechahasta, string productos, string idusuario) {
            base.Channel.web_listarpedidos(codigoempresa, idrepartodesde, idrepartohasta, fechadesde, fechahasta, productos, idusuario);
        }
        
        public void web_controlruta(string codigoempresa, string fecha, int idreparto, int tiporesultado, int orden, string idusuario) {
            base.Channel.web_controlruta(codigoempresa, fecha, idreparto, tiporesultado, orden, idusuario);
        }
        
        public void web_stockcontrol(string codigoempresa, string fecha, int idreparto) {
            base.Channel.web_stockcontrol(codigoempresa, fecha, idreparto);
        }
        
        public void web_stockcontroldetalle(string codigoempresa, int idreparto) {
            base.Channel.web_stockcontroldetalle(codigoempresa, idreparto);
        }
        
        public void web_stockcontrolequipos(string codigoempresa, int idreparto) {
            base.Channel.web_stockcontrolequipos(codigoempresa, idreparto);
        }
        
        public void web_stockcontrolhistoria(string codigoempresa, int idreparto, string idproducto) {
            base.Channel.web_stockcontrolhistoria(codigoempresa, idreparto, idproducto);
        }
        
        public void web_stockcontroleliminarequipo(string codigoempresa, int idreparto, long idrecarga) {
            base.Channel.web_stockcontroleliminarequipo(codigoempresa, idreparto, idrecarga);
        }
        
        public void web_stockcontrolinsertar(string codigoempresa, int idreparto, string idproducto, long lleno_bulto, long lleno_suelto, long vacio_bulto, long vacio_suelto, long desdereparto) {
            base.Channel.web_stockcontrolinsertar(codigoempresa, idreparto, idproducto, lleno_bulto, lleno_suelto, vacio_bulto, vacio_suelto, desdereparto);
        }
        
        public void web_stockcontrolinsertarequipo(string codigoempresa, int idreparto, string idproducto, string nro_serie) {
            base.Channel.web_stockcontrolinsertarequipo(codigoempresa, idreparto, idproducto, nro_serie);
        }
        
        public void web_mensajeinsertar(string codigoempresa, int idreparto, string idusuario, string mensaje) {
            base.Channel.web_mensajeinsertar(codigoempresa, idreparto, idusuario, mensaje);
        }
        
        public void web_repartosporsupervisor(string codigoempresa, string idusuario) {
            base.Channel.web_repartosporsupervisor(codigoempresa, idusuario);
        }
        
        public void web_insertarreparto_supervisor(string codigoempresa, string idusuario, string idsupervisor) {
            base.Channel.web_insertarreparto_supervisor(codigoempresa, idusuario, idsupervisor);
        }
        
        public void web_borrarreparto_supervisor(string codigoempresa, string idusuario, string idsupervisor) {
            base.Channel.web_borrarreparto_supervisor(codigoempresa, idusuario, idsupervisor);
        }
        
        public void web_mensajeborrar(string codigoempresa, string idmensaje) {
            base.Channel.web_mensajeborrar(codigoempresa, idmensaje);
        }
        
        public void web_mensajelistar(string codigoempresa, string idusuario) {
            base.Channel.web_mensajelistar(codigoempresa, idusuario);
        }
        
        public void web_getubicacion_repartos(string codigoempresa, string idusuario) {
            base.Channel.web_getubicacion_repartos(codigoempresa, idusuario);
        }
        
        public void web_getruta_real(string codigoempresa, string fecha, string idusuario) {
            base.Channel.web_getruta_real(codigoempresa, fecha, idusuario);
        }
        
        public void web_topesfiadolistar(string codigoempresa, string idrepartodesde, string idrepartohasta, int clientesdeldia, string idusuario) {
            base.Channel.web_topesfiadolistar(codigoempresa, idrepartodesde, idrepartohasta, clientesdeldia, idusuario);
        }
        
        public void web_topesfiado_actualizar(string codigoempresa, string tope_aviso, string tope_bloqueo, string minimo_cobrar, string idcliente) {
            base.Channel.web_topesfiado_actualizar(codigoempresa, tope_aviso, tope_bloqueo, minimo_cobrar, idcliente);
        }
        
        public void web_agregarruta(string codigoempresa, string usuario, string rtoprimario, string diaprimario, string rtosecundario, string diasecundario) {
            base.Channel.web_agregarruta(codigoempresa, usuario, rtoprimario, diaprimario, rtosecundario, diasecundario);
        }
        
        public void web_agregarrutaeliminar(string codigoempresa, string usuario, string idcambioruta) {
            base.Channel.web_agregarrutaeliminar(codigoempresa, usuario, idcambioruta);
        }
        
        public void web_agregarrutalistar(string codigoempresa, string idusuario) {
            base.Channel.web_agregarrutalistar(codigoempresa, idusuario);
        }
        
        public void web_informaciongeneralgrilla(string codigoempresa, string usuario) {
            base.Channel.web_informaciongeneralgrilla(codigoempresa, usuario);
        }
        
        public void web_usuarioactualizar(
                    string codigoempresa, 
                    string idusuario, 
                    string idperfil, 
                    string nombre, 
                    string usuario, 
                    string idvendedor, 
                    int editaprecio, 
                    int sincargo, 
                    int minutosmax, 
                    string passsup, 
                    int habfc, 
                    int repuniversal, 
                    int habremito, 
                    int habfactura, 
                    int habfacturaelectronica, 
                    int habrecibo, 
                    int habremitocontado, 
                    int habfacrempagocontado, 
                    string iibb, 
                    string pass, 
                    int trabaja_madrugada, 
                    int oculta_totales_estadistica, 
                    int oculta_novisitar, 
                    string idsupervisor, 
                    int total_clientes) {
            base.Channel.web_usuarioactualizar(codigoempresa, idusuario, idperfil, nombre, usuario, idvendedor, editaprecio, sincargo, minutosmax, passsup, habfc, repuniversal, habremito, habfactura, habfacturaelectronica, habrecibo, habremitocontado, habfacrempagocontado, iibb, pass, trabaja_madrugada, oculta_totales_estadistica, oculta_novisitar, idsupervisor, total_clientes);
        }
        
        public void web_usuarioeliminar(string codigoempresa, string idusuario) {
            base.Channel.web_usuarioeliminar(codigoempresa, idusuario);
        }
        
        public void web_usuarioslistar(string codigoempresa, string idusuario) {
            base.Channel.web_usuarioslistar(codigoempresa, idusuario);
        }
        
        public void web_usuarios_modifmasivapass(string codigoempresa, int idperfil, int tipopass, string pass, string idusuario) {
            base.Channel.web_usuarios_modifmasivapass(codigoempresa, idperfil, tipopass, pass, idusuario);
        }
        
        public void web_motivos_nocompra_actualizar(string codigoempresa, int idmotivo, string descripcion, int orden, int cierrallamado) {
            base.Channel.web_motivos_nocompra_actualizar(codigoempresa, idmotivo, descripcion, orden, cierrallamado);
        }
        
        public void web_motivos_nocompra_eliminar(string codigoempresa, int idmotivo) {
            base.Channel.web_motivos_nocompra_eliminar(codigoempresa, idmotivo);
        }
        
        public void web_motivos_nocompra_listar(string codigoempresa) {
            base.Channel.web_motivos_nocompra_listar(codigoempresa);
        }
        
        public void web_motivos_recambio_actualizar(string codigoempresa, int idmotivo, string descripcion, int orden) {
            base.Channel.web_motivos_recambio_actualizar(codigoempresa, idmotivo, descripcion, orden);
        }
    }
}
